# Generated by Django 6.1.1 on 2026-09-13 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('codigo_nomenclador', models.CharField(blank=True, help_text='Código nomenclador nacional (preparado)', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Obra Social / Prepaga',
                'verbose_name_plural': 'Obras Sociales / Prepagas',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('dni', models.CharField(help_text='DNI / Documento de Identidad', max_length=20, unique=True)),
                ('telefono', models.CharField(help_text='Número móvil para recordatorios por WhatsApp (ej: +5491112345678)', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('numero_afiliado', models.CharField(blank=True, help_text='Número de credencial/afiliado (preparado)', max_length=100, null=True)),
                ('datos_contacto_adicionales', models.TextField(blank=True, help_text='Contacto de emergencia, tutor o allegado')),
                ('consentimiento_datos', models.BooleanField(default=True, help_text='Consentimiento de tratamiento de datos según Ley 25.326')),
                ('consentimiento_fecha', models.DateTimeField(auto_now_add=True)),
                ('consentimiento_ip', models.GenericIPAddressField(default='127.0.0.1')),
                ('proxima_fecha_recall', models.DateField(blank=True, help_text='Fecha sugerida para el próximo control médico preventivo', null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('obra_social', models.ForeignKey(blank=True, help_text='Obra social o prepaga (preparado)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='pacientes.obrasocial')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
    ]
