# Generated by Django 5.0.14 on 2026-09-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Marca de borrado lógico para auditoría y cumplimiento legal'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='consentimiento_datos',
            field=models.BooleanField(default=False, help_text='Consentimiento de tratamiento de datos según Ley 25.326'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='consentimiento_fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='consentimiento_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
