# Generated by Django 6.1.1 on 2026-09-13 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('duracion_minutos', models.IntegerField(default=30)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado'), ('ATENDIDO', 'Atendido'), ('AUSENTE', 'Ausente / No asistió'), ('EN_ESPERA', 'En Sala de Espera')], default='PENDIENTE', max_length=20)),
                ('notificado_wsp_medico', models.BooleanField(default=False)),
                ('notificado_wsp_paciente', models.BooleanField(default=False)),
                ('en_lista_espera', models.BooleanField(default=False, help_text='Anotado en lista de espera si se libera un turno')),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('consultorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='usuarios.consultorio')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='usuarios.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='pacientes.paciente')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='usuarios.sede')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['fecha', 'hora'],
            },
        ),
        migrations.CreateModel(
            name='FacturaConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comprobante', models.CharField(blank=True, help_text='Factura A, B, C (preparado AFIP)', max_length=20, null=True)),
                ('cae', models.CharField(blank=True, help_text='Código de Autorización Electrónico AFIP (preparado)', max_length=50, null=True)),
                ('monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('turno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='turnos.turno')),
            ],
            options={
                'verbose_name': 'Factura de Consulta',
                'verbose_name_plural': 'Facturas de Consulta',
            },
        ),
    ]
