# Generated by Django 5.0.14 on 2026-09-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Marca de borrado lógico para auditoría y cumplimiento legal'),
        ),
    ]
