# Generated by Django 6.1.1 on 2026-09-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_consultorio', models.CharField(default='Consultorio Médico San Lucas', max_length=200)),
                ('max_medicos_permitidos', models.IntegerField(default=2, help_text='Cupo máximo de médicos habilitados. Cambiar a 10 o a 0 (sin límite) según la licencia.')),
                ('telefono_whatsapp_empresa', models.CharField(blank=True, default='+5491100000000', max_length=50)),
                ('direccion_consultorio', models.CharField(blank=True, default='Av. Corrientes 1234, CABA, Argentina', max_length=300)),
                ('modo_demo', models.BooleanField(default=True, help_text='Indica si el sistema está operando en modo demostración con datos iniciales de prueba.')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
    ]
