# Generated by Django 6.1.1 on 2026-09-13 00:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateTimeField(default=django.utils.timezone.now)),
                ('motivo_consulta', models.TextField(help_text='Motivo de la consulta reportado por el paciente')),
                ('notas_evolucion', models.TextField(blank=True, help_text='Examen físico, observaciones y evolución')),
                ('diagnostico', models.TextField(help_text='Diagnóstico o hipótesis diagnóstica')),
                ('tratamiento_prescrito', models.TextField(blank=True, help_text='Indicaciones médicas y tratamiento')),
                ('receta_electronica', models.TextField(blank=True, help_text='Texto / formato de receta electrónica (preparado)', null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Marca de borrado lógico para auditoría y cumplimiento legal')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='historias_atendidas', to='usuarios.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias_clinicas', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Historia Clínica',
                'verbose_name_plural': 'Historias Clínicas',
                'ordering': ['-fecha_consulta'],
            },
        ),
    ]
