# Generated by Django 6.1.1 on 2026-09-13 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Especialidad Médica',
                'verbose_name_plural': 'Especialidades Médicas',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=250)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('matricula_profesional', models.CharField(help_text='Matrícula Nacional o Provincial', max_length=50)),
                ('telefono_whatsapp', models.CharField(help_text='Número con código de país (ej: +5491112345678)', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('google_calendar_id', models.CharField(blank=True, help_text='Preparado para sync futura', max_length=255, null=True)),
                ('especialidades', models.ManyToManyField(related_name='medicos', to='usuarios.especialidad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_medico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
            },
        ),
        migrations.CreateModel(
            name='MedicoSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_atencion', models.CharField(help_text='Ej: Lunes, Miércoles, Viernes', max_length=100)),
                ('horario_inicio', models.TimeField()),
                ('horario_fin', models.TimeField()),
                ('duracion_turno_default', models.IntegerField(default=30, help_text='Duración estándar del turno en minutos')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_sede', to='usuarios.medico')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_medicos', to='usuarios.sede')),
            ],
            options={
                'verbose_name': 'Horario de Atención por Sede',
                'verbose_name_plural': 'Horarios de Atención por Sede',
            },
        ),
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_numero', models.CharField(help_text='Ej: Consultorio 102 - Planta Alta', max_length=100)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultorios', to='usuarios.sede')),
            ],
            options={
                'verbose_name': 'Consultorio (Sala Física)',
                'verbose_name_plural': 'Consultorios (Salas Físicas)',
            },
        ),
    ]
