# Generated by Django 6.1.1 on 2026-09-13 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(help_text='CREAR / EDITAR / ELIMINAR / VER / EXPORTAR', max_length=50)),
                ('entidad', models.CharField(help_text='Ej: HistoriaClinica, Paciente, Turno', max_length=100)),
                ('entidad_id', models.CharField(blank=True, max_length=50, null=True)),
                ('detalles', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_origen', models.GenericIPAddressField(default='127.0.0.1')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-timestamp'],
            },
        ),
    ]
