# Generated by Django 5.0.14 on 2026-09-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logauditoria',
            name='hash_integridad',
            field=models.CharField(blank=True, help_text='SHA-256 para verificar integridad del registro', max_length=64),
        ),
    ]
